### ISSUE TITLE
need Android watch version



### ISSUE THREAD

**Issue by stark4x** [DevEmperor/WristAssist#14]
I have a oppo watch4pro based on Android 11, 

really wanna try it.

**Comment by stark4x** [comment]
thx for the reply, I need the apk file to run it on android watch. 
the oppo watch is based on andriod without google playstore and gms.
it's a bit different with wearos...

**Comment by DevEmperor** [comment]
Hey, that sounds strange to me. I'll send you a link to download the APK anyway so that you can use the app. Of course, updates are not included. Let me know if that worked.
I have published the app in the PlayStore for a small amount, so I would appreciate a small honest donation [via PayPal](https://paypal.me/DevEmperor). :)
Have fun with WristAssist!

https://workupload.com/file/5NXnmLYU93X
The link only works once, after that the file will be deleted... ;)
