### ISSUE TITLE
Start screen on every launch

### ISSUE THREAD

**Issue by Batyan45** [DevEmperor/WristAssist#18]
Is it normal that I see start screen (Welcome to WristAssist) and API key request on every launch?

I want to ask a quick question, but it takes a lot of time with all screens :)

I have a custom api server, can it be a reason?

**Comment by DevEmperor** [comment]
That is indeed a weird error. It can't actually be due to the custom API server, I've just tried to reproduce the problem, but it doesn't happen for me.
Can you go to the About Activity and long press on the WristAssist logo? Then your user ID will appear so that I can better analyse the problem in the logs. :)

**Comment by Batyan45** [comment]
Ok :)

838804606

**Comment by DevEmperor** [comment]
Okay, I see in the logs that WristAssist has not saved that the onboarding ("Welcome to WristAssist") has been completed. This can only be because you didn't enter an API key when you were first asked to do so.
To solve the problem, you should enter an API key the next time you start the app, when the onboarding appears again, so that WristAssist remembers that you have completed the first start. Only then should you set a custom API server or another API key.
Please let me know if this worked. :)

**Comment by Batyan45** [comment]
Yes, this worked, thanks! :)
