### ISSUE TITLE
on click New Chat get a Black screen

### ISSUE THREAD

**Issue by Jetiman** [DevEmperor/WristAssist#3]
I use the Galaxy Watch 6 classic.  When I click on new chat I get a black screen.  The app is still running, I can swipe back.

Ich nutze die Galaxy Watch 6 classic. Wenn ich auf Neuer Chat klicke bekomme ich ein schwarzen Bildschirm. Die app läuft noch, ich kann zurück wischen.

**Comment by Jetiman** [comment]
Edit: Found a bug.  I selected the gboard keyboard.  It works with the Samsung keyboard

**Comment by DevEmperor** [comment]
Hey, thanks for pointing that out. I've had my eye on the bug since the first version. Unfortunately, I think the bug lies with Google GBoard, as I use the official code to open the keyboard. For me, it always works the second time I open it, when the keyboard doesn't appear the first time. Try that out, otherwise the Samsung keyboard works too, of course. 

I am testing the app with a Samsung Galaxy Watch 4 LTE.
