### ISSUE TITLE
gboard isnt working you should improve your appp :D

### ISSUE THREAD

**Issue by Someonetoldme584** [DevEmperor/WristAssist#4]
gboard isnt working you should improve your appp :D

**Comment by DevEmperor** [comment]
Hey, thanks for pointing out this mistake. As described in #3, the problem is not in my code. It's a problem with Google's GBoard that I can't do much about, unfortunately.
For me, the keyboard still works if you swipe back once and then click on "New Chat" again. Or you can use a different keyboard, such as the Samsung Keyboard.

P.S. A more detailed error description would be useful too... ;)

**Comment by Someonetoldme584** [comment]
Jannis Zahn ***@***.***>, 16 Eyl 2023 Cmt, 09:34 tarihinde
şunu yazdı:

**Comment by Someonetoldme584** [comment]
Actually samsung keyboard is working but the voice thing only support english i want to use turkish

**Comment by DevEmperor** [comment]
Okay, I'll do some more research and see what I can do about that bug.
