### ISSUE TITLE
Function added

### ISSUE THREAD

**Issue by AnujMuth** [DevEmperor/WristAssist#6]
I found that expressions can be recognized. So, if the uploaded image recognition function is added to the input interface, can it also be used?

**Comment by DevEmperor** [comment]
Thank you for the question. Unfortunately, I couldn't really understand what feature you were suggesting. Could you be more specific in your question about exactly which feature you want me to add?

**Comment by AnujMuth** [comment]
Is it possible to add the function of uploading pictures to identify pictures?

**Comment by DevEmperor** [comment]
Unfortunately, this feature is not possible because OpenAI does not provide an API interface for uploading images as input to GPT-4. This function is highly anticipated by the entire community, but we will have to wait a little longer.

https://help.openai.com/en/articles/7127995-how-can-i-use-gpt-4-with-images
https://community.openai.com/t/gpt-4-api-and-image-input/102852/11
